use anchor_lang::prelude::*;

pub mod errors;
pub mod events;
pub mod instructions;
pub mod state;

// Glob-re-export every instruction module so that the `__client_accounts_*`
// modules generated by `#[derive(Accounts)]` are visible at the crate root,
// as required by Anchor 0.29's `#[program]` macro expansion.
pub use instructions::buy_ido::*;
pub use instructions::claim_ido_tokens::*;
pub use instructions::finalize_ido::*;
pub use instructions::initialize_ido::*;
pub use instructions::pause_ido::*;
pub use instructions::refund_ido::*;

declare_id!("Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS");

#[program]
pub mod membra_ido {
    use super::*;

    /// Create and configure a new IDO.
    ///
    /// # Parameters
    /// - `token_price_usd_6`   – Price per IDO token in USDC micro-units (6 dec).
    /// - `hard_cap_tokens`     – Maximum tokens available for sale.
    /// - `min_purchase_tokens` – Minimum tokens a wallet can buy in a single call.
    /// - `max_purchase_tokens` – Maximum tokens a wallet may buy in total.
    /// - `start_ts`            – Unix timestamp when the sale opens.
    /// - `end_ts`              – Unix timestamp when the sale closes.
    /// - `claim_start_ts`      – Unix timestamp when token claims open (>= end_ts).
    /// - `unsold_burn`         – If `true`, unsold tokens are burned at finalization;
    ///                           otherwise they are transferred to the treasury.
    pub fn initialize_ido(
        ctx: Context<InitializeIdo>,
        token_price_usd_6: u64,
        hard_cap_tokens: u64,
        min_purchase_tokens: u64,
        max_purchase_tokens: u64,
        start_ts: i64,
        end_ts: i64,
        claim_start_ts: i64,
        unsold_burn: bool,
    ) -> Result<()> {
        instructions::initialize_ido::handler(
            ctx,
            token_price_usd_6,
            hard_cap_tokens,
            min_purchase_tokens,
            max_purchase_tokens,
            start_ts,
            end_ts,
            claim_start_ts,
            unsold_burn,
        )
    }

    /// Purchase IDO tokens by depositing USDC into the payment vault.
    ///
    /// # Parameters
    /// - `token_amount` – Number of IDO tokens to purchase (in raw token units).
    pub fn buy_ido(ctx: Context<BuyIdo>, token_amount: u64) -> Result<()> {
        instructions::buy_ido::handler(ctx, token_amount)
    }

    /// Finalize the IDO after it has ended.
    ///
    /// Burns or transfers unsold tokens according to `unsold_burn` and marks
    /// the IDO as finalized, enabling token claims.
    pub fn finalize_ido(ctx: Context<FinalizeIdo>) -> Result<()> {
        instructions::finalize_ido::handler(ctx)
    }

    /// Claim purchased IDO tokens after finalization and the claim window opens.
    pub fn claim_ido_tokens(ctx: Context<ClaimIdoTokens>) -> Result<()> {
        instructions::claim_ido_tokens::handler(ctx)
    }

    /// Refund a buyer's USDC deposit if the IDO has been cancelled.
    pub fn refund_ido(ctx: Context<RefundIdo>) -> Result<()> {
        instructions::refund_ido::handler(ctx)
    }

    /// Pause or resume the IDO (authority / governance only).
    ///
    /// # Parameters
    /// - `pause` – `true` to pause the IDO; `false` to resume it.
    pub fn pause_ido(ctx: Context<PauseIdo>, pause: bool) -> Result<()> {
        instructions::pause_ido::handler(ctx, pause)
    }
}
