//! # MEMBRA Governance Program
//!
//! A production-quality multisig governance and treasury authorization program
//! for the MEMBRA Money Protocol.
//!
//! ## Core invariant
//! No treasury action can be taken without going through the full
//! **propose → approve → timelock → execute** flow.  There is no backdoor; no
//! admin can bypass governance.
//!
//! ## Architecture
//! This program is a **pure authorization layer**.  It does not move funds or
//! modify parameters in other programs directly.  Instead:
//!
//! 1. A registered signer creates a `Proposal` describing the desired action.
//! 2. Signers add approvals until the threshold is met, transitioning the
//!    proposal to `Approved` and starting the timelock clock.
//! 3. After the timelock elapses (and before the execution window closes) any
//!    registered signer calls `execute_approved_action`, which marks the
//!    proposal `Executed`.
//! 4. The **target program** (IDO, Rebase, Rewards, …) reads the `Proposal`
//!    PDA on-chain, verifies its status is `Executed`, and only then permits
//!    the privileged operation.
//!
//! This design keeps cross-program invocation (CPI) complexity out of the
//! governance layer while still enforcing the governance invariant on-chain.

use anchor_lang::prelude::*;

pub mod errors;
pub mod events;
pub mod instructions;
pub mod state;

// Glob-re-export every instruction module so that the `__client_accounts_*`
// modules generated by `#[derive(Accounts)]` are visible at the crate root,
// as required by Anchor 0.29's `#[program]` macro expansion.
pub use instructions::approve_action::*;
pub use instructions::cancel_action::*;
pub use instructions::execute_approved_action::*;
pub use instructions::initialize_governance::*;
pub use instructions::propose_action::*;

use state::ActionType;

declare_id!("Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkj476zPFsLnS");

// ---------------------------------------------------------------------------
// Program entry points
// ---------------------------------------------------------------------------

#[program]
pub mod membra_governance {
    use super::*;

    // -----------------------------------------------------------------------
    // initialize_governance
    // -----------------------------------------------------------------------

    /// Creates and initialises the [`GovernanceConfig`] PDA for a given authority.
    ///
    /// This is a **one-time** operation per authority keypair.  Subsequent
    /// changes to governance parameters (signers, threshold, timelock) must go
    /// through a governance proposal with `ActionType::UpdateGovernanceParams`.
    ///
    /// # Parameters
    /// - `signers`                  – ordered list of multisig signer pubkeys (1..=10).
    /// - `approval_threshold`       – minimum approvals needed (1..=len(signers)).
    /// - `timelock_seconds`         – delay after approval before execution (≥ 0;
    ///                                recommend ≥ 86 400 for mainnet).
    /// - `execution_window_seconds` – window after timelock expires during which
    ///                                execution is permitted (> 0; recommend ≥ 172 800).
    /// - `treasury`                 – the treasury pubkey this governance oversees.
    pub fn initialize_governance(
        ctx: Context<InitializeGovernance>,
        signers: Vec<Pubkey>,
        approval_threshold: u8,
        timelock_seconds: i64,
        execution_window_seconds: i64,
        treasury: Pubkey,
    ) -> Result<()> {
        instructions::initialize_governance::handler(
            ctx,
            signers,
            approval_threshold,
            timelock_seconds,
            execution_window_seconds,
            treasury,
        )
    }

    // -----------------------------------------------------------------------
    // propose_action
    // -----------------------------------------------------------------------

    /// Creates a new governance proposal.
    ///
    /// Only registered signers may call this instruction.  When the governance
    /// is paused, only [`ActionType::EmergencyPause`] proposals may be created.
    ///
    /// # Parameters
    /// - `action_type`   – the category of action being proposed.
    /// - `description`   – human-readable rationale (≤ 255 UTF-8 bytes).
    /// - `action_data`   – serialised action-specific parameters (≤ 255 bytes).
    /// - `proposal_id`   – must equal `governance_config.proposal_count` at call
    ///                     time; used as the PDA seed component.
    pub fn propose_action(
        ctx: Context<ProposeAction>,
        action_type: ActionType,
        description: String,
        action_data: Vec<u8>,
        proposal_id: u64,
    ) -> Result<()> {
        instructions::propose_action::handler(
            ctx,
            action_type,
            description,
            action_data,
            proposal_id,
        )
    }

    // -----------------------------------------------------------------------
    // approve_action
    // -----------------------------------------------------------------------

    /// Records the calling signer's approval of a `Pending` proposal.
    ///
    /// When the approval count reaches the governance threshold the proposal
    /// automatically transitions to `Approved` and `approved_ts` is set,
    /// starting the timelock countdown.
    pub fn approve_action(ctx: Context<ApproveAction>) -> Result<()> {
        instructions::approve_action::handler(ctx)
    }

    // -----------------------------------------------------------------------
    // execute_approved_action
    // -----------------------------------------------------------------------

    /// Marks an `Approved` proposal as `Executed` after the timelock elapses.
    ///
    /// The calling signer must be registered in the governance config.  The
    /// proposal must be in `Approved` status, the timelock must have elapsed,
    /// and the execution window must not have expired.
    ///
    /// **No funds are transferred here.**  This instruction is a pure
    /// authorization marker.  Target programs verify the `Executed` status
    /// of the proposal PDA before permitting privileged operations.
    pub fn execute_approved_action(ctx: Context<ExecuteApprovedAction>) -> Result<()> {
        instructions::execute_approved_action::handler(ctx)
    }

    // -----------------------------------------------------------------------
    // cancel_action
    // -----------------------------------------------------------------------

    /// Cancels a `Pending` or `Approved` proposal.
    ///
    /// - Any registered signer may cancel a `Pending` proposal.
    /// - Cancelling an `Approved` proposal requires that the existing approval
    ///   count still meets the threshold (i.e. the same consensus that approved
    ///   must implicitly agree to cancel).
    /// - Terminal proposals (`Executed`, `Cancelled`, `Expired`) cannot be cancelled.
    pub fn cancel_action(ctx: Context<CancelAction>) -> Result<()> {
        instructions::cancel_action::handler(ctx)
    }
}
